In [6]:
import pandas as pd

In [7]:
df_1=pd.read_csv("../DATA/SYMPTOMS/disease_symptoms.csv")

In [8]:
df_1.shape

(40, 18)

In [10]:
df_1.columns

Index(['Disease', 'Symptom_1', 'Symptom_2', 'Symptom_3', 'Symptom_4',
       'Symptom_5', 'Symptom_6', 'Symptom_7', 'Symptom_8', 'Symptom_9',
       'Symptom_10', 'Symptom_11', 'Symptom_12', 'Symptom_13', 'Symptom_14',
       'Symptom_15', 'Symptom_16', 'Symptom_17'],
      dtype='str')

In [11]:
df_1.head()

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Allergy,continuous_sneezing,shivering,chills,watering_from_eyes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,GERD,stomach_pain,acidity,ulcers_on_tongue,vomiting,cough,chest_pain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Chronic cholestasis,itching,vomiting,yellowish_skin,nausea,loss_of_appetite,abdominal_pain,yellowing_of_eyes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Drug Reaction,itching,skin_rash,stomach_pain,burning_micturition,spotting_ urination,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df_1.isnull().sum()

Disease        0
Symptom_1      0
Symptom_2      0
Symptom_3      0
Symptom_4      0
Symptom_5      8
Symptom_6     14
Symptom_7     21
Symptom_8     24
Symptom_9     26
Symptom_10    28
Symptom_11    29
Symptom_12    33
Symptom_13    35
Symptom_14    38
Symptom_15    38
Symptom_16    38
Symptom_17    39
dtype: int64

In [13]:
df_1["Disease"].nunique()

40

In [14]:
df_1["Disease"].unique()

<StringArray>
[                       'Fungal infection',
                                 'Allergy',
                                    'GERD',
                     'Chronic cholestasis',
                           'Drug Reaction',
                     'Peptic ulcer diseae',
                                    'AIDS',
                               'Diabetes ',
                         'Gastroenteritis',
                        'Bronchial Asthma',
                           'Hypertension ',
                                'Migraine',
                    'Cervical spondylosis',
            'Paralysis (brain hemorrhage)',
                                'Jaundice',
                                 'Malaria',
                             'Chicken pox',
                                  'Dengue',
                                 'Typhoid',
                             'hepatitis A',
                             'Hepatitis B',
                             'Hepatitis C',
                             'Hepatitis D',
                             'Hepatitis E',
                     'Alcoholic hepatitis',
                            'Tuberculosis',
                             'Common Cold',
                               'Pneumonia',
            'Dimorphic hemmorhoids(piles)',
                            'Heart attack',
                          'Varicose veins',
                          'Hypothyroidism',
                            'Hypoglycemia',
                         'Osteoarthristis',
                               'Arthritis',
 '(vertigo) Paroymsal  Positional Vertigo',
                                    'Acne',
                 'Urinary tract infection',
                               'Psoriasis',
                                'Impetigo']
Length: 40, dtype: str

In [15]:
df=pd.read_csv("../DATA/SYMPTOMS/Disease and symptoms dataset.csv")

In [16]:
df.shape

(246945, 378)

In [17]:
df.columns

Index(['diseases', 'anxiety and nervousness', 'depression',
       'shortness of breath', 'depressive or psychotic symptoms',
       'sharp chest pain', 'dizziness', 'insomnia',
       'abnormal involuntary movements', 'chest tightness',
       ...
       'stuttering or stammering', 'problems with orgasm', 'nose deformity',
       'lump over jaw', 'sore in nose', 'hip weakness', 'back swelling',
       'ankle stiffness or tightness', 'ankle weakness', 'neck weakness'],
      dtype='str', length=378)

In [18]:
df.head

<bound method NDFrame.head of                       diseases  anxiety and nervousness  depression  \
0               panic disorder                        1           0
1               panic disorder                        0           0
2               panic disorder                        1           1
3               panic disorder                        1           0
4               panic disorder                        1           1
...                        ...                      ...         ...
246940  open wound of the nose                        0           0
246941  open wound of the nose                        0           0
246942  open wound of the nose                        0           0
246943  open wound of the nose                        0           0
246944  open wound of the nose                        0           0

        shortness of breath  depressive or psychotic symptoms  \
0                         1                                 1
1                         1                                 1
2                         1                                 1
3                         0                                 1
4                         0                                 0
...                     ...                               ...
246940                    0                                 0
246941                    0                                 0
246942                    0                                 0
246943                    0                                 0
246944                    0                                 0

        sharp chest pain  dizziness  insomnia  abnormal involuntary movements  \
0                      0          0         0                               0
1                      0          1         1                               0
2                      0          1         1                               0
3                      0          1         1                               1
4                      0          0         1                               1
...                  ...        ...       ...                             ...
246940                 0          0         0                               0
246941                 0          0         0                               0
246942                 0          0         0                               0
246943                 0          0         0                               0
246944                 0          0         0                               0

        chest tightness  ...  stuttering or stammering  problems with orgasm  \
0                     1  ...                         0                     0
1                     0  ...                         0                     0
2                     0  ...                         0                     0
3                     0  ...                         0                     0
4                     1  ...                         0                     0
...                 ...  ...                       ...                   ...
246940                0  ...                         0                     0
246941                0  ...                         0                     0
246942                0  ...                         0                     0
246943                0  ...                         0                     0
246944                0  ...                         0                     0

        nose deformity  lump over jaw  sore in nose  hip weakness  \
0                    0              0             0             0
1                    0              0             0             0
2                    0              0             0             0
3                    0              0             0             0
4                    0              0             0             0
...                ...            ...           ...           ...
246940               0              0             0             0
246941               0              0             0             0
246942               0              0             0             0
246943               0              0             0             0
246944               0              0             0             0

        back swelling  ankle stiffness or tightness  ankle weakness  \
0                   0                             0               0
1                   0                             0               0
2                   0                             0               0
3                   0                             0               0
4                   0                             0               0
...               ...                           ...             ...
246940              0                             0               0
246941              0                             0               0
246942              0                             0               0
246943              0                             0               0
246944              0                             0               0

        neck weakness
0                   0
1                   0
2                   0
3                   0
4                   0
...               ...
246940              0
246941              0
246942              0
246943              0
246944              0

[246945 rows x 378 columns]>

In [19]:
df.head()

,diseases,anxiety and nervousness,depression,shortness of breath,depressive or psychotic symptoms,sharp chest pain,dizziness,insomnia,abnormal involuntary movements,chest tightness,...,stuttering or stammering,problems with orgasm,nose deformity,lump over jaw,sore in nose,hip weakness,back swelling,ankle stiffness or tightness,ankle weakness,neck weakness
0,panic disorder,1,0,1,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,panic disorder,0,0,1,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,panic disorder,1,1,1,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,panic disorder,1,0,0,1,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
4,panic disorder,1,1,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0

In [20]:
df.dtypes.value_counts()

int64    377
str        1
Name: count, dtype: int64

In [21]:
df["diseases"].nunique()

773

In [22]:
df["diseases"].value_counts()

diseases
cystitis                          1219
vulvodynia                        1218
nose disorder                     1218
complex regional pain syndrome    1217
spondylosis                       1216
                                  ...
foreign body in the nose             1
thalassemia                          1
open wound of the head               1
rocky mountain spotted fever         1
kaposi sarcoma                       1
Name: count, Length: 773, dtype: int64

In [23]:
df["diseases"].value_counts().describe()

count     773.000000
mean      319.463131
std       351.691549
min         1.000000
25%        30.000000
50%       168.000000
75%       505.000000
max      1219.000000
Name: count, dtype: float64

In [24]:
counts = df["diseases"].value_counts()

print("Diseases with 1-9 samples:", ((counts >= 1) & (counts <= 9)).sum())
print("Diseases with 10-29 samples:", ((counts >= 10) & (counts <= 29)).sum())
print("Diseases with 30-49 samples:", ((counts >= 30) & (counts <= 49)).sum())
print("Diseases with 50-99 samples:", ((counts >= 50) & (counts <= 99)).sum())
print("Diseases with 100-199 samples:", ((counts >= 100) & (counts <= 199)).sum())
print("Diseases with 200-499 samples:", ((counts >= 200) & (counts <= 499)).sum())
print("Diseases with 500+ samples:", (counts >= 500).sum())

Diseases with 1-9 samples: 96
Diseases with 10-29 samples: 95
Diseases with 30-49 samples: 55
Diseases with 50-99 samples: 84
Diseases with 100-199 samples: 82
Diseases with 200-499 samples: 160
Diseases with 500+ samples: 201

In [28]:
min_samples=50
disease_count=df["diseases"].value_counts()
valid_diseases=disease_count[disease_count>=min_samples].index
df_filtered = df[df["diseases"].isin(valid_diseases)]
print("Original rows:", len(df))
print("Filtered rows:", len(df_filtered))
print("Original diseases:", df["diseases"].nunique())
print("Filtered diseases:", df_filtered["diseases"].nunique())

Original rows: 246945
Filtered rows: 242837
Original diseases: 773
Filtered diseases: 527

In [30]:
df_filtered.iloc[:, 1:].stack().value_counts()

0    90245251
1     1304298
Name: count, dtype: int64

In [31]:
df_filtered.isnull().sum().sum()

np.int64(0)

In [32]:
df_filtered.duplicated().sum()

np.int64(54799)

In [33]:
symptom_columns = df_filtered.columns[1:]

duplicate_groups = (
    df_filtered
    .groupby(list(symptom_columns))["diseases"]
    .nunique()
)

conflicting_groups = duplicate_groups[duplicate_groups > 1]

print("Duplicate symptom patterns:", len(duplicate_groups))
print("Conflicting symptom patterns:", len(conflicting_groups))

Duplicate symptom patterns: 168751
Conflicting symptom patterns: 12444

In [34]:

conflict_rows = (
    df_filtered
    .merge(
        conflicting_groups.rename("disease_count"),
        left_on=list(symptom_columns),
        right_index=True
    )
)

print("Rows belonging to conflicting patterns:", len(conflict_rows))
print("Percentage of dataset:", round(len(conflict_rows) / len(df_filtered) * 100, 2), "%")

Rows belonging to conflicting patterns: 38557
Percentage of dataset: 15.88 %

In [35]:
conflicting_groups.value_counts().sort_index()

diseases
2     8803
3     2163
4      738
5      351
6      174
7       95
8       42
9       28
10      18
11       6
12       8
13       3
14       7
15       1
16       1
17       1
20       2
21       1
22       2
Name: count, dtype: int64

In [36]:
df_clean = df_filtered.drop_duplicates()

print("Rows before removing duplicates:", len(df_filtered))
print("Rows after removing duplicates:", len(df_clean))
print("Rows removed:", len(df_filtered) - len(df_clean))
print("Diseases remaining:", df_clean["diseases"].nunique())

Rows before removing duplicates: 242837
Rows after removing duplicates: 188038
Rows removed: 54799
Diseases remaining: 527

In [37]:
X = df_clean.iloc[:, 1:]
y = df_clean["diseases"]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (188038, 377)
y shape: (188038,)

In [38]:
df_clean.head()

,diseases,anxiety and nervousness,depression,shortness of breath,depressive or psychotic symptoms,sharp chest pain,dizziness,insomnia,abnormal involuntary movements,chest tightness,...,stuttering or stammering,problems with orgasm,nose deformity,lump over jaw,sore in nose,hip weakness,back swelling,ankle stiffness or tightness,ankle weakness,neck weakness
0,panic disorder,1,0,1,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,panic disorder,0,0,1,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,panic disorder,1,1,1,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,panic disorder,1,0,0,1,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
4,panic disorder,1,1,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0

In [39]:
X=df_clean.iloc[:,1:]
Y=df_clean["diseases"]
print("X shape:",X.shape)
print("Y shape:",Y.shape)

X shape: (188038, 377)
Y shape: (188038,)

In [40]:
from sklearn.preprocessing import LabelEncoder
label_encoder=LabelEncoder()
y_encoded=label_encoder.fit_transform(y)
print("Number of disease classes:", len(label_encoder.classes_))
print("First 10 disease names:", label_encoder.classes_[:10])
print("First 10 encoded labels:", y_encoded[:10])
print("Encoded y shape:", y_encoded.shape)

Number of disease classes: 527
First 10 disease names: ['abdominal aortic aneurysm' 'abdominal hernia' 'abscess of nose'
 'abscess of the pharynx' 'achalasia' 'acne' 'actinic keratosis'
 'acute bronchiolitis' 'acute bronchitis' 'acute bronchospasm']
First 10 encoded labels: [359 359 359 359 359 359 359 359 359 359]
Encoded y shape: (188038,)

In [45]:
print(label_encoder.inverse_transform([359]))
print(label_encoder.transform(["panic disorder"]))

['panic disorder']
[359]

In [46]:
print("Cleaned dataset shape:", df_clean.shape)
print("Missing values:", df_clean.isnull().sum().sum())
print("Duplicate rows:", df_clean.duplicated().sum())
print("Number of diseases:", df_clean["diseases"].nunique())

Cleaned dataset shape: (188038, 378)
Missing values: 0
Duplicate rows: 0
Number of diseases: 527

In [48]:
df_clean.to_csv("../DATA/SYMPTOMS/data_symptoms_clean.csv",index=False)
print("clean dataset saved successfully")

clean dataset saved successfully